### DISCUSSION TITLE
使用config_updater.py生成额外的活动图任务

### DISCUSSION THREAD

**Discussion by ChthoIly** [LmeSzinc/AzurLaneAutoScript#4229] [Q&A] [answered]
我想给调度器添加额外的活动图任务。

![image](https://github.com/user-attachments/assets/7e63ca2a-42f5-46f3-800a-0cbc6877b8c1)

默认有“活动图”，“活动图-2”。我希望添加“活动图-3”。

我看了[开发文档关于GUI Option的部分](https://github.com/LmeSzinc/AzurLaneAutoScript/wiki/6.1.-GUI-Option)，文档中提到使用config_updater.py来生成程序需要的json文件。根据文中提到的：

> 需要开发者手动编写的有：
> 
> task.yaml，定义每个任务所包含的选项组
> argument.yaml，定义每个选项组包含的选项，以及每个选项的属性
> override.yaml，覆盖某些特殊选项的值，比如硬编码服务器刷新时间
> gui.yaml，定义 GUI 上会出现的其他文本

我手动编辑了task.yaml和override.yaml。其余的两个文件并没有新加东西因为我没有发现有相关需要更改的地方。

```
task.yaml
# ==================== Event ====================

Event:
  menu: 'collapse'
  page: 'setting'
  tasks:
    EventGeneral:
      - EventGeneral
      - TaskBalancer
    Event:
      - Scheduler
      - Campaign
      - StopCondition
      - Fleet
      - Submarine
      - Emotion
      - HpControl
      - EnemyPriority
    Event2:
      - Scheduler
      - Campaign
      - StopCondition
      - Fleet
      - Submarine
      - Emotion
      - HpControl
      - EnemyPriority
    Event3:
      - Scheduler
      - Campaign
      - StopCondition
      - Fleet
      - Submarine
      - Emotion
      - HpControl
      - EnemyPriority
```

```
overide.yaml
# ==================== Event ====================

Event:
  Campaign:
    Mode: normal
    Event:
      type: state
    AmbushEvade: true
Event2:
  Campaign:
    Mode: normal
    Event:
      type: state
    AmbushEvade: true
Event3:
  Campaign:
    Mode: normal
    Event:
      type: state
    AmbushEvade: true
```

简单的复制粘贴，把对应的活动图2的代码部分复制并修改名称为活动图3。之后我运行了config_updater.py并确认相关的args.json和template.json已经有相应的内容，但是生成的任务活动名称并不是活动图的而是主线图的。

![image](https://github.com/user-attachments/assets/bb449428-fbe2-4fe7-985a-1f21610c82fe)

如图：可以看见关卡设置中的活动名称文本和提示是正确的，如果是主线图的模板并不会有活动名称这一板块。但是我并不能调出活动名称的下拉菜单来选择对应的活动。我可以通过手动修改args.json来手动添加对应的活动：

```
      "Event": {
        "type": "state",
        "value": "campaign_main",
        "option": [
          "event_20200227_cn",
          "event_20200312_cn",
          "event_20200326_cn",
          "event_20200423_cn",
          "event_20200507_cn",
          "event_20200521_cn",
          "event_20200521_en",
          "event_20200603_cn",
          "event_20200603_en",
          "event_20200611_en",
          "event_20200716_en",
          "event_20200723_cn",
          "event_20200806_cn",
          "event_20200820_cn",
          "event_20200903_en",
          "event_20200917_cn",
          "event_20201002_en",
          "event_20201012_cn",
          "event_20201029_cn",
          "event_20201126_cn",
          "event_20201229_cn",
          "event_20210121_cn",
          "event_20210225_cn",
          "event_20210225_tw",
          "event_20210325_cn",
          "event_20210415_tw",
          "event_20210422_cn",
          "event_20210429_tw",
          "event_20210527_cn",
          "event_20210527_tw",
          "event_20210610_tw",
          "event_20210624_cn",
          "event_20210624_tw",
          "event_20210722_cn",
          "event_20210819_cn",
          "event_20210916_cn",
          "event_20211028_cn",
          "event_20211028_tw",
          "event_20211111_cn",
          "event_20211125_cn",
          "event_20211229_cn",
          "event_20220210_cn",
          "event_20220224_cn",
          "event_20220310_tw",
          "event_20220324_cn",
          "event_20220407_tw",
          "event_20220414_cn",
          "event_20220428_cn",
          "event_20220526_cn",
          "event_20220728_cn",
          "event_20220818_cn",
          "event_20220915_cn",
          "event_20221124_cn",
          "event_20221222_cn",
          "event_20230223_cn",
          "event_20230525_cn",
          "event_20230803_cn",
          "event_20230817_cn",
          "event_20230914_cn",
          "event_20231026_cn",
          "event_20231123_cn",
          "event_20231221_cn",
          "event_20240229_cn",
          "event_20240425_cn",
          "event_20240521_cn",
          "event_20240725_cn",
          "event_20240815_cn",
          "event_20240829_cn",
          "event_20240912_cn"
        ],
        "option_bold": [
          "event_20230914_cn",
          "event_20240912_cn"
        ],
        "cn": "event_20240912_cn",
        "en": "event_20240912_cn",
        "jp": "event_20240912_cn",
        "tw": "event_20230914_cn"
      },
```

但是正如开发文档中说的

> args.json 是由 config_updater.py 生成的，每次修改选项后，都应该运行 config_updater.py 来生成，而不是手动修改 args.json。

args.json并不应该被手动修改，而是一个由config_updater.py生成。我该如何正确的编辑几个yaml文件来使config_updater.py生成正确的活动图任务？
