### ISSUE TITLE
求适配ntfy

### ISSUE THREAD

**Issue by W1NDes** [LmeSzinc/AzurLaneAutoScript#3380]
### 你的功能请求是否与问题有关？

求适配onepush系统适配[ntfy](https://ntfy.sh/)
使用webhook自定义模式下不能很好的让ntfy推送显示为理想样式

(或者是不是我的使用方式错误了？)

### 解决方案

配置文件我是这样写的：
```
provider: custom
url: https://ntfy.sh
method: post
data:             
  topic: xxxxx  #此处填ntfy推送的主题码
```
但是ntfy的消息内容是message，而module/notify.py中是content，导致ntfy的推送消息只有标题，没有内容
```
if "content" in kwargs:
    config["data"]["content"] = kwargs["content"]
```

### 其他内容

[ntfy推送json格式的说明：](https://docs.ntfy.sh/publish/#publish-as-json)
![image](https://github.com/LmeSzinc/AzurLaneAutoScript/assets/122395784/1328d520-6c9d-4d4e-9a21-b89a22ec97bf)

**Comment by dawn-lc** [comment]
https://github.com/y1ndan/onepush/commit/cd5f4c3dcc0ed63c4f82f4bb9893c7a90eec6446

onepush现已支持，本项目是否更新onepush？

目前我的使用方式
```
provider: custom
url: https://username:password@ntfy.domain/
method: post
data:
  topic: "alas"
  message: "自定义信息"
  priority: 4
```
